name: pfg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - notebook
  - numba
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - ipython
prefix: /Users/kweemstra/miniconda3/envs/pfg
